name = "mil"
defaultTargets = ["MIL", "LeanBook"] # デフォルトでビルドする対象に追加

[leanOptions]
pp.unicode.fun = true
#autoImplicit = false
#relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.21.0"

[[lean_lib]]
name = "MIL"
srcDir = "mathematics_in_lean" # このフォルダ内のファイルを MIL モジュールとして扱う

# 追加の設定：LeanBook フォルダ用
[[lean_lib]]
name = "LeanBook"
# srcDir を指定しない場合、プロジェクトのルートにある LeanBook フォルダを探します
# もし LeanBook/LeanBook.lean のような構成なら以下のように指定します
# srcDir = "LeanBook"

[[lean_lib]]
name = "TPIL"